# This workflow validates the examples against the RNG schema
# this is probably more proof-of-conceptish than actually useful, since one would expect
# validation to happen even before a push. For the same reason, I don't want to dynamically
# create the RNG from ODD, simply because I also expect this to be done before a push 
# (or a pull request). But, who knows where we end up, so here's a piece of working functionality

name: validate_MAF_examples

# Controls when the action will run. Triggers the workflow on push or pull request
# events, for the master branch and also for the test branch (which can be created to
# test some stuff, then deleted, and again.
on:
  push:
    branches: [master,  test]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.5.2
        - name: a guessing game
          run: |
            echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            ls
 
