# This is a basic workflow to help you get started with Actions

name: validate_examples

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master,  test]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # install the necessary stuff
    - name: install libxml2
      run: sudo apt-get install libxml2-utils

    # validate
    - name: Validate with xmllint --noout --xinclude 
      run: xmllint --noout --xinclude --relaxng $GITHUB_WORKSPACE/MAFinTEI.rng $GITHUB_WORKSPACE/MAFinTEI-examples.xml

